### ISSUE TITLE
save single frame (.raw) as numpy array (N, 400,400)

### ISSUE THREAD

**Issue by lrlunin** [lrlunin/pytango-moenchZmqServer#3]
looks like this library will be helpful...
https://pypi.org/project/npy-append-array/

**Comment by lrlunin** [comment]
However, if frames will be written to the array sequentially from many processes, there is a question of how to sort frames in the right order. It seems to be easier to have a single buffer `buffer_single_raw_frames` Nx400x400, where N is obviously more than the number of frames that can be received in one session. Then each thread will write `buffer_single_raw_frames[frame_index] = raw_single_frame`. This will require some condition on the minimum RAM again for the workstation. For example for a 10000x400x400 buffer
`np.zeros([10000, 400,400], dtype=np.uint16).nbytes = 320000000000` approx. 3GB. 

Than this single array will be saved with `np.save(...)` without any additional troubles. On my personal PC with nvme SSD it took $1.92 \pm 3$ ms.

**Comment by dschick** [comment]
it is super important, that the raw data will be saved in the correct order as tagged by the moench.
So I would first allocate the Nx400x400 array and then sort all frames into it before saving it.
Ideally, saving happens after the evaluated data is provided to Sardana, so the time for saving is not necessarily blocking the acquisition.

**Comment by lrlunin** [comment]
Just tested on the moench HDD write of [N, 400, 400] array with:
| N| write on HDD [sec]  | write on SSD [sec] | integration equivalent with 100Hz [sec] |
|-|-|-|-|
|2500|0.67| 0.43 | 25|
|5000|1.3 | 0.85 | 50|
|10000|2.6| 1.72 | 100| 

I guess that 1% of exposure time overhead is not really critical while creating buffer for each acquisition series, handling of in the background, potential memory leak or/and time wasted with garbage collection can take the same 1% of the time. I guess the first implementation with just saving this array in single thread is okay.

I agree that later it should be done in the background while the next acquisition is already running. But I guess there can be problems if we will acquire with extremely low integration times (less than 10 frames) and disk access time will be comparable with integration time. Then yes, we will lose much time (in relative terms).

**Comment by dschick** [comment]
Is the limitation to 10000 frames necessary?

**Comment by dschick** [comment]
Okay, so it should be dynamical and must throw an error if it exceeds a certain ram limit.

**Comment by lrlunin** [comment]
In order to have a safe variant to store `.raw` data the oncoming packets can be forwarded to `slsReceiver` instance to save data in convenient format and be sure that it is working as expected.

**Comment by dschick** [comment]
btw, is `.npy` the optimal choice as data format? how about `hdf5`?
I have no idea about the performance comparison ...

**Comment by lrlunin** [comment]
Good idea! then we are able to save the capture nr as well. I will run the benchmarks to compare the speed. It's also important to check which of the format is better compatible with `dask` if we will probably process the raw frames with it.

**Comment by lrlunin** [comment]
.h5 library and format allows to parallel thread safe writing to the same file. It is the best variant for the data storage what will make post processing much easier involving tools like pyevaldata or pymca.

https://docs.h5py.org/en/stable/mpi.html

**Comment by lrlunin** [comment]
see https://docs.python.org/3/library/mmap.html
perhaps can be useful

**Comment by lrlunin** [comment]
resolved in 4e50278c47697b8d77c8dcbc6e448dc3c9506e61 with the working but not really the cleanest and beautiful solution
